### ISSUE TITLE
Allow multiple mattermost tokens

### ISSUE THREAD

**Issue by amaddio-zz** [M-Mueller/mattermost-poll#10]
If you want this MM integration to be added to more than one MM team you need the ability to specify more than just one token in the config file. As for now you have to add a slash command manually to each MM team which generates an individual token. You would have to run the same mattermost-poll python web application several times. One for each MM team.

I think it would make sense most to amend the code so that you can specify several MM tokens _MATTERMOST_TOKEN_ argument in _settings.py_. Has anyone already implemented such thing and cares for a pull request? Otherwise I would change the code and publish it here in case you are interested for merge?

**Comment by M-Mueller** [comment]
Good point. You can create a PR if you want. Otherwise I can take a look on the weekend.

**Comment by amaddio-zz** [comment]
Up to you. I won't have time to solve the problem today unfortunately. I'll think I'll get to it the following week. We can just play it by ear. Let's see. Thanks for considering a pull request. TTY soon

**Comment by M-Mueller** [comment]
I added a branch for this (team_tokens). Can you if this works for you? Thanks.

**Comment by amaddio-zz** [comment]
@M-Mueller seems to be working fine 👍 I use the integration in six teams now. Thanks for the quick response and implementation. I think we can merge it to the main branch so that others might benefit from your change too. Thanks bunches.

**Comment by amaddio-zz** [comment]
Also double checked with a team where the token has not been added to the config. I correctly get 
the message saying: 

> The integration is not correctly set up: Invalid token.  

So working really fine in my opinion :bowtie:

**Comment by M-Mueller** [comment]
Great! I will merge the branch and create a new release.
