### ISSUE TITLE
Command with a trigger of 'poll' failed

### ISSUE THREAD

**Issue by gervmex** [M-Mueller/mattermost-poll#11]
Hey,

I have problems starting a poll. I have installed all requirements and updated everything. Mattermost is also running on the newest version. Mattermost-poll is installed on the same server as Mattermost. The error I get in the mattermost.log is `[EROR] /api/v4/commands/execute:command code=500 rid=cu9cbomk83rjbdf8scunptoghr uid=jh5y7phshbgu7qa8xwfj3uro6h ip='MyIPaddress' Command with a trigger of 'poll' failed [details: Post http://localhost:5001: address forbidden]`
I also checked the Mattermost-poll error.log but no error is logged, except I try opening http://'Serveraddress':5001 then I get `WARNING:tornado.access:405 GET / (192.168.33.1) 2.33ms`

I hope you have an idea what the problem could be...

Best,
Max

**Comment by M-Mueller** [comment]
Did you add http://localhost:5001 to _AllowedUntrustedInternalConnections_ in you Mattermost config.json?

**Comment by gervmex** [comment]
Thank you for your fast answer! Yes we did, but its not working with or without.
When i open http://'Serveraddress':5001, "Method Not Allowed     The method is not allowed for the requested URL" is shown.

**Comment by M-Mueller** [comment]
Could you try if this works:
```
curl -X POST --data "command=poll&text=help&user_id=1" http://'Serveraddress':5001
```
This should send you the help text back if the poll server works.
_edit: data was wrong_

**Comment by gervmex** [comment]
That's what I get:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
```

**Comment by M-Mueller** [comment]
This is very weird. Does this also happen when you run the curl command directly on the server?
I just added a simple GET method. If you now open the URL in your browser it should display some text.

**Comment by gervmex** [comment]
Both runs on the same server so there is no other server. When I now open the Url it returns "Poll server is running"

**Comment by M-Mueller** [comment]
Just realized my previous comment was wrong. The [AllowedUntrustedInternalConnections](https://docs.mattermost.com/administration/config-settings.html#allow-untrusted-internal-connections-to) line should look like this, without the http and port:
```
"AllowedUntrustedInternalConnections": "localhost",
```
I also tried with the latest Mattermost version but still works for me. Since you can reach the URL, I think the problem is somewhere in the Mattermost configuration or maybe a firewall setting.

**Comment by gervmex** [comment]
Thank you!! `"AllowedUntrustedInternalConnections": "localhost",` Fixed it !!
