### ISSUE TITLE
Poll ends after one vote

### ISSUE THREAD

**Issue by gervmex** [M-Mueller/mattermost-poll#12]
Hey,

we now have the problem that after one person votes, the vote is ended immediately and not even the voting summary is shown. The error.log and the mattermost.log do not show any errors ..

I hope you have an idea what the problem could be...

Best,
Max

**Comment by M-Mueller** [comment]
Can you please add the following to your `settings.py` to enable file logging:
```
import logging
logging.basicConfig(filename='poll.log', level=logging.DEBUG)
```

**Comment by gervmex** [comment]
I already did that and named it error.log. Once I open a poll and vote the following is shown in the error.log:

> INFO:app:Creating Poll: 21
INFO:tornado.access:200 POST / (127.0.0.1) 7.68ms
INFO:app:Voting in poll "21" for user "p6h3gpq7gtgezbu55ucaezfy6e": 0
INFO:tornado.access:200 POST /vote (127.0.0.1) 3.90ms
INFO:app:Creating Poll: 22
INFO:tornado.access:200 POST / (127.0.0.1) 9.87ms
INFO:app:Voting in poll "22" for user "bhj4onbuy3fx3nq63qbyofjjdy": 1
INFO:tornado.access:200 POST /vote (127.0.0.1) 4.56ms
DEBUG:asyncio:Using selector: EpollSelector

**Comment by M-Mueller** [comment]
I couldn't reproduce this yet. What is happening exactly? Does the poll just disappear completely or are just the buttons disappearing?

**Comment by gervmex** [comment]
![bildschirmfoto 2018-03-26 um 09 15 58 kopie](https://user-images.githubusercontent.com/37405863/37892035-c08604be-30d6-11e8-95f9-d6c38d2bec1b.jpg)
When I create the vote and someone hits yes or no then this is what is shown. there are no buttons to end this poll. Also when you add a higher number of votes for each person, the poll ends after one vote.

**Comment by M-Mueller** [comment]
I think there is something wrong with the response data. I extended the logging, could you try again and upload the log? Thanks.

**Comment by gervmex** [comment]
Thanks for your help! Here is the log.
[logging.txt](https://github.com/M-Mueller/mattermost-poll/files/1851015/logging.txt)

**Comment by M-Mueller** [comment]
I cannot reproduce this. The logged data looks fine. I also used it as a hardcoded response and the buttons remain. What really confuses me, is that only the buttons disappear but the *Number of voters* field is updated correctly. Maybe check that you are really running the latest Mattermost version (v4.8.0). 

You can also try to run the unit tests with
```
pip3 install -r tests/requirements.txt
python3 -m pytest
```
Additionally you can run the server directly with flask instead of the run.py (which uses tornado):
```
FLASK_DEBUG=1 FLASK_APP=app.py flask-3 run --host=0.0.0.0 -p 5001
```
Hope that helps.

**Comment by gervmex** [comment]
Thanks Allot for your Help! We now have reinstalled Mattermost and now its working fine!!
