### ISSUE TITLE
is there installation manual for idiots?

### ISSUE THREAD

**Issue by hexo4yxa1** [M-Mueller/mattermost-poll#14]
I have followed instructions, but poll is not working for me. I am getting poll finished with error.
Question is about settings.py
I have a mattermost on xx.xx.xx.xx:8065
WEBSERVER_ADDRESS shall I use my IP xx.xx.xx.xx
on WEBSERVER_PORT shall I leave 5000 - or use 865 instead
What about MATTERMOST_URL - I am using xx.xx.xx.xx:8065 - is it correct?
And in mattermost integration section shall i use
http://xx.xx.xx.xx:5000
or http://xx.xx.xx.xx:8065
Please addvice.
Thank you

**Comment by M-Mueller** [comment]
I'm assuming you are running mattermost and mattermost-poll on the same machine? In this case you can leave WEBSERVER_ADDRESS as '0.0.0.0'. 

As port you can use any port that is not taken by another application (you will get a Permission Denied error on startup otherwise). So you cannot use 8065 since this is already used by your Mattermost server. If 5000 doesn't work use 5001, 5002..., doesn't really matter.

For MATTERMOST_URL use 'http://xx.xx.xx.xx:8065'.

In the mattermost integration settings you use 'http://xx.xx.xx.xx:5000' as URL (replace 5000 with the port you use for WEBSERVER_PORT) and select POST as method.

Finally, go to 'System Console' in Mattermost 'Advanced -> Developer' (last entry) and add your IP (xx.xx.xx.xx) to the 'Allow untrusted internal connections' field.

**Comment by hexo4yxa1** [comment]
Thank you for your answer. Did like you have explained, but when I try to run.py - it s don't run. Just stops. After some waiting I am stopping it with commant Ctrl+C and getting this message. I'm sorry to bother you once again, but maybe you could advice 
root@chat:~/poll/mattermost-poll-master# python3 run.py
^CTraceback (most recent call last):
  File "run.py", line 12, in <module>
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.4/dist-packages/tornado/platform/asyncio.py", lin                  e 112, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 244, in run_forever
    self._run_once()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 1049, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.4/selectors.py", line 424, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
root@chat:~/poll/mattermost-poll-master# python run.py
^CTraceback (most recent call last):
  File "run.py", line 12, in <module>
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.4/dist-packages/tornado/platform/asyncio.py", lin                  e 112, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 244, in run_forever
    self._run_once()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 1049, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.4/selectors.py", line 424, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt

**Comment by M-Mueller** [comment]
This is normal, the server doesn't print anything on startup. To check if it is reachable, you can go to http://xx.xx.xx.xx:5000 in your browser and should see a status message.

**Comment by hexo4yxa1** [comment]
Strange. I'm getting Poll server is running message.
But when I try to make a poll like this /poll question --answer1 --answer2 or even just /poll question 
I am gettig error message The command with the 'poll' trigger ended with an error
Don't you know what is the reason of this issue? Thank you for your helping, I'm really appreciate it

**Comment by M-Mueller** [comment]
Is there something on the console? When you access it in your browser there should be something like:
> INFO:tornado.access:200 GET /

and when you issue the slash command in mattermost something like

> INFO:tornado.access:200 POST /

**Comment by hexo4yxa1** [comment]
ah, just saw it
yes, but there is only 1 error
WARNING:tornado.access:404 GET /favicon.ico (109.201.178.81) 1.93ms
not sure favicon could be a reason, but it is all 
Now I have tried to make a poll once again, and there is no any messages, even about favicon.

**Comment by M-Mueller** [comment]
The warning about the favicon is fine (not needed by mattermost).
Can you uncomment the last to two lines in the settings.py that enables file logging? I think the INFO messages are not enabled by default.

**Comment by hexo4yxa1** [comment]
I have enabled logging and this is entry from a log file

DEBUG:asyncio:Using selector: EpollSelector
INFO:tornado.access:200 GET / (109.201.178.81) 2.22ms

**Comment by M-Mueller** [comment]
Ok, so there is probably something wrong with setup of the slash command in Mattermost. Make sure you use the correct Request URL (including http:// and the correct port). Also check that the IP is part of 'Allow untrusted internal connections' (here without http:// and port).

**Comment by hexo4yxa1** [comment]
You said earlier 
Is there something on the console? When you access it in your browser there should be something like:
INFO:tornado.access:200 GET /

And as I can see - there GET not POST in error.
Also I have a question - in this error INFO:tornado.access:200 GET / (109.201.178.81) 2.22ms
It is not my IP address. Don't you know what is this? Maybe this address somewhere I didn't changed?
My IP another. If it is possible, can I give you access information to check it - maybe by e-mail or any other ways?

**Comment by M-Mueller** [comment]
I don't really have time to do this now. Does your mattermost server run on the same computer that you are using for the poll server (that is where you call run.py)?

**Comment by hexo4yxa1** [comment]
ok, I understand. Yes, it is on the same computer

**Comment by M-Mueller** [comment]
Then try these settings:
```
DATABASE = 'polls.db'
WEBSERVER_ADDRESS = '0.0.0.0'
WEBSERVER_PORT = 5000
MATTERMOST_TOKENS = None
MATTERMOST_URL = 'http://localhost:8065'
MATTERMOST_PA_TOKEN = None
```
And in Mattermost configure the slash command with the following settings:
Request URL: http://localhost:5000
Request Method: POST

Then set 'System Console' -> 'Advanced' -> 'Developer' -> 'Allow untrusted internal connections' to `localhost`.

**Comment by hexo4yxa1** [comment]
yes yes, thank you so much. It works now. 
What about script - I shall add it to rc.local to run it automatically?

**Comment by M-Mueller** [comment]
Either that your create [service file](https://www.devdungeon.com/content/creating-systemd-service-files) (if your distribution uses systemd).
