### ISSUE TITLE
Mattermost API v4

### ISSUE THREAD

**Issue by amaddio-zz** [M-Mueller/mattermost-poll#15]
We are planning on updating to Mattermost Server v5.0. On step on a successfull migration is to make sure that all integrations use Mattermost API v4 endpoints. It is described here: https://api.mattermost.com/#tag/APIv3-Deprecation. I have looked through the code and can find only on api endpoint call which already goes to v4:

> /api/v4/users/ids

So I'd guess that the integration is good to go for Mattermost 5.0. Would be much appreciated if you could confirm that?

**Comment by M-Mueller** [comment]
Yes, this is the only place where the API is used. I could not find any release notes for v5.0 yet, but I think it's very unlikely that it will break the integration.

**Comment by amaddio-zz** [comment]
Thanks for your feedback.
