### ISSUE TITLE
Can this be wrapped into a plugin?

### ISSUE THREAD

**Issue by uhlhosting** [M-Mueller/mattermost-poll#17]
Is this possible to have it as a Mattermost plugin? Or no plans to add such integration?

**Comment by M-Mueller** [comment]
I checked the documentation and it seems that for now plugins must be written in Go. What would be the advantage anyway?

**Comment by uhlhosting** [comment]
@M-Mueller I can see the only and main advantage is portability, and since Mattermost just starts to improve plugin platform, would be easier to implement, and once not needed to remove, all this without interacting with CLI or with any server.

**Comment by M-Mueller** [comment]
I think for now it is too much work. However, I will keep it in mind for once the plugin API is out of beta.
