### ISSUE TITLE
mattermost-poll as docker image

### ISSUE THREAD

**Issue by Rachitmehrotra** [M-Mueller/mattermost-poll#25]
I have tried to use the mattermost-poll directly and it was working fine but when i have created as docker image and try to run it was not giving any output could you please let me know if i need to do anything extra or missing something.

**Comment by M-Mueller** [comment]
Can you please post the command you used to build the image and run the container?

**Comment by Rachitmehrotra** [comment]
I am using ur Dockerfile to build the docker image,
docker build -t mattermostpoll .
when i run the container on some port like 5000 inside the container i m able to get the output but outside the container, I m not.

**Comment by M-Mueller** [comment]
Did you publish the port when running the container? E.g.:
```
docker run -p 5000:5000 mattermostpoll
```
