### ISSUE TITLE
bars are too big

### ISSUE THREAD

**Issue by silberzwiebel** [M-Mueller/mattermost-poll#34]
As can be seen in this screenshot from a desktop PC, the bars are too big to be a useful visualization.
![bildschirmfoto-20190214180152-1428x825](https://user-images.githubusercontent.com/4533862/52803679-ccb7f380-3082-11e9-97ff-53c9b885d98d.png)

Could you make them smaller? Thanks!

**Comment by M-Mueller** [comment]
This seems to be a regression in Mattermost 5.7: https://github.com/mattermost/mattermost-server/issues/10355

**Comment by silberzwiebel** [comment]
Okay, thanks for hunting it! I'll see if I can upgrade to 5.8 soon and report back then.

**Comment by M-Mueller** [comment]
Seems to work again with Mattermost 5.8

**Comment by silberzwiebel** [comment]
Confirming!
