### ISSUE TITLE
local bars are not shown

### ISSUE THREAD

**Issue by silberzwiebel** [M-Mueller/mattermost-poll#35]
Leaving `BAR_IMG_URL` at its default value (`None`) leads to a broken image, as it unsuccessfully tries to serve `http://localhost:5001/img/bar.png`:

![bildschirmfoto-20190214181338-889x702](https://user-images.githubusercontent.com/4533862/52804333-456b7f80-3084-11e9-8066-76828b9427e2.png)

Am I doing something wrong here?

**Comment by M-Mueller** [comment]
Can you try this with Mattermost 5.8? With the new [image proxy support](https://mattermost.com/blog/mattermost-5-8/#image) the image is loaded by the server and the local URL should work then.

**Comment by silberzwiebel** [comment]
Yes, it works now, thanks!
