### ISSUE TITLE
bars are not shown in the android app

### ISSUE THREAD

**Issue by silberzwiebel** [M-Mueller/mattermost-poll#36]
Regardless of setting `BAR_IMG_URL` or not, in the android app (version 1.15.2) I only see markdown code and no bar image:
![f9df8062_tn0kvrnnq4mrvvvf52nq_w](https://user-images.githubusercontent.com/4533862/52804580-d80c1e80-3084-11e9-9f86-88b6df2dbd00.jpg)

**Comment by M-Mueller** [comment]
Can you please try to just post `![Bar](https://raw.githubusercontent.com/M-Mueller/mattermost-poll/master/img/bar.png =450x25)` directly in the android app? Maybe the app does not support image sizes through markdown.
Unfortunately I don't have an android phone to test this myself.

**Comment by silberzwiebel** [comment]
The markdown command works fine (except that the bar is still too large but thats #34): 
![5158103_fzt7keaorlcot4oxcqgjvg](https://user-images.githubusercontent.com/4533862/53351595-d31b5a80-3921-11e9-984a-05f6827eab04.jpg)

**Comment by M-Mueller** [comment]
Weird. As far as understand it, the android app uses the same react code as the web version. It also works on Firefox mobile. Would you mind opening an issue in mattermost-mobile?

**Comment by silberzwiebel** [comment]
I had a quick look for potential duplicates at `mattermost/mattermost-mobile` and found these two:

https://github.com/mattermost/mattermost-mobile/issues/1951
https://github.com/mattermost/mattermost-mobile/issues/2568

Could you have a look if these issues already capture the bug? Thanks!
