### ISSUE TITLE
allow team- or system-admins to end all polls

### ISSUE THREAD

**Issue by silberzwiebel** [M-Mueller/mattermost-poll#38]
Right now, only the user who started the poll can close it, others (even if system administrator) get a message that they are not allowed to do so.
Could you add an option that allows to end other user's polls at least for system- or team-admins?
Thanks!

**Comment by M-Mueller** [comment]
Sounds reasonable since the admin is already allowed to delete the poll completely. I think there is something in API to check if a user is an admin.
