### ISSUE TITLE
Bars are broken with mattermost 5.18.0

### ISSUE THREAD

**Issue by matclab** [M-Mueller/mattermost-poll#41]
After updating to mattermost 5.18.0, the bars of existing and new pooll do not appear (or more precisely they are all 1 pixel wide regardless of the result).

**Comment by M-Mueller** [comment]
Could you check if the markdown for resizing still works when you post a message with this content:
```
![Bar](https://raw.githubusercontent.com/M-Mueller/mattermost-poll/master/img/bar.png =450x25)
```

**Comment by matclab** [comment]
I just tried and the bar is still 1px wide.

**Comment by matclab** [comment]
There is a bug report upstream : https://github.com/mattermost/mattermost-server/issues/13539
and https://mattermost.atlassian.net/browse/MM-21421.
Thee is also a PR available : mattermost/mattermost-webapp#4623.

I guess we can wait the next release and close this bug.

**Comment by M-Mueller** [comment]
Less work for me then :smiley:. I will leave this open until it's fixed upstream. Thanks for investigating!

**Comment by M-Mueller** [comment]
Works again with 5.19
