### ISSUE TITLE
Failed to resolve usernames

### ISSUE THREAD

**Issue by negativ72rus** [M-Mueller/mattermost-poll#9]
in "--public" polls have error "Failed to resolve usernames"
MATTERMOST_PA_TOKEN is provided in settings.py
what else could be the problem?

**Comment by M-Mueller** [comment]
Is there an error message or exception in the log?
Could be that the MATTERMOST_URL is not reachable. If you are using docker, this could be caused by using http://localhost as MATTERMOST_URL.

**Comment by negativ72rus** [comment]
![image](https://user-images.githubusercontent.com/12546951/36834969-73e8d2f0-1d56-11e8-8ed8-76490adf9a5f.png)
Is there an error message
MATTERMOST_URL set in settings.py

**Comment by M-Mueller** [comment]
Sorry, I meant an error message in the log of the server.

**Comment by negativ72rus** [comment]
but where exactly should I look? in the mattermost.log nothing

**Comment by M-Mueller** [comment]
By default the poll server will only log to stdout (e.g. the console). If you start the server through systemctl it ends up in journalctl.
You can also log to a file by adding the following to your settings.py:
```
import logging
logging.basicConfig(filename='error.log', level=logging.DEBUG)
```

**Comment by negativ72rus** [comment]
Thanks, now we will try.

**Comment by negativ72rus** [comment]
that's what we saw in the logs, but it's not clear what to do with this:
`[2018-03-01 09:29:21,826] ERROR in app: Username query failed: No connection adapters were found for '10.101.1.6:8000/api/v4/users/ids'`

**Comment by M-Mueller** [comment]
Does your MATTERMOST_URL start with http://?

**Comment by negativ72rus** [comment]
Now I'll check, I understand that I should start with http://?

**Comment by M-Mueller** [comment]
Yes, in your case probably
```
MATTERMOST_URL = 'http://10.101.1.6:8000'
```

**Comment by negativ72rus** [comment]
Hooray! It works now! Thank you so much!
